// SPDX-FileCopyrightText: 2025 Dreykor <160512778+Dreykor@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 GabyChangelog <agentepanela2@gmail.com>
// SPDX-FileCopyrightText: 2025 Kyoth25f <kyoth25f@gmail.com>
// SPDX-FileCopyrightText: 2025 Tyranex <bobthezombie4@gmail.com>
// SPDX-FileCopyrightText: 2025 funkystationbot <funky@funkystation.org>
//
// SPDX-License-Identifier: MIT

using System.Linq;
using System.Numerics;
using Content.Client.MalfAI.Theme;
using Content.Client.Stylesheets;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Gabystation.MalfAI.IntrinsicVoiceModulator;

[GenerateTypedNameReferences]
public sealed partial class IntrinsicVoiceModulatorWindow : DefaultWindow
{
    [Dependency] private readonly IResourceCache _resCache = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;

    private readonly SpriteSystem _spriteSystem;

    public event Action<string>? OnNameChanged;
    public event Action<ProtoId<JobIconPrototype>>? OnJobIconChanged;

    private const int JobIconColumnCount = 10;
    private ProtoId<JobIconPrototype>? _currentJobIconId;

    public IntrinsicVoiceModulatorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _spriteSystem = _entitySystem.GetEntitySystem<SpriteSystem>();

        // Apply Malf theme: backdrop without static, button style without static, fonts & accent tint.
        RootBackdrop.PanelOverride = MalfUiTheme.CreateBackdropStyle();

        // Add scrolling error backdrop behind all UI elements - insert at beginning so it appears behind
        var errorBackdrop = MalfEffectOverlay.CreateErrorBackdrop();
        RootBackdrop.AddChild(errorBackdrop);
        errorBackdrop.SetPositionInParent(0); // Move to first position (behind all other elements)

        // Add CRT static overlay using the unified effect system - this stays on top
        var staticOverlay = MalfEffectOverlay.CreateStaticOverlay();
        RootBackdrop.AddChild(staticOverlay);
        var buttonStyle = MalfUiTheme.CreateButtonStyle(MalfUiTheme.Accent);

        // Apply Malf stylesheet
        RootBackdrop.Stylesheet = MalfUiTheme.GetCachedStylesheet(_resCache, 12);
    }

    public void SetAllowedIcons(string currentJobIconId)
    {
        IconGrid.DisposeAllChildren();

        var jobIconButtonGroup = new ButtonGroup();
        var i = 0;
        var icons = _prototypeManager.EnumeratePrototypes<JobIconPrototype>().Where(icon => icon.AllowSelection).ToList();
        icons.Sort((x, y) => string.Compare(x.LocalizedJobName, y.LocalizedJobName, StringComparison.CurrentCulture));
        foreach (var jobIcon in icons)
        {
            var styleBase = StyleBase.ButtonOpenBoth;
            var modulo = i % JobIconColumnCount;
            if (modulo == 0)
                styleBase = StyleBase.ButtonOpenRight;
            else if (modulo == JobIconColumnCount - 1)
                styleBase = StyleBase.ButtonOpenLeft;

            // Generate buttons
            var jobIconButton = new Button
            {
                Access = AccessLevel.Public,
                StyleClasses = { styleBase },
                MaxSize = new Vector2(42, 28),
                Group = jobIconButtonGroup,
                Pressed = currentJobIconId == jobIcon.ID,
                ToolTip = jobIcon.LocalizedJobName
            };

            // Generate buttons textures
            var jobIconTexture = new TextureRect
            {
                Texture = _spriteSystem.Frame0(jobIcon.Icon),
                TextureScale = new Vector2(2.5f, 2.5f),
                Stretch = TextureRect.StretchMode.KeepCentered,
            };

            jobIconButton.AddChild(jobIconTexture);
            jobIconButton.OnPressed += _ => OnJobIconChanged?.Invoke(jobIcon.ID);
            IconGrid.AddChild(jobIconButton);

            i++;
        }
    }

    public void SetCurrentName(string name)
    {
        NameLineEdit.Text = name;
    }
}
